### ISSUE TITLE
[debt]Enable emit of .glob (linkage)

### ISSUE THREAD

**Issue by krasin** [llvm-dcpu16/llvm-dcpu16#49]
Currently, emiting linkage is disabled in lib/CodeGen/AsmPrinter/AsmPrinter.cpp, AsmPrinter::EmitLinkage, because DCPU16 assemblers are immature and don't support it.

This issue is to track the local mod and remove it when possible.

**Comment by krasin** [comment]
Related commit is a518658bf88bbaf42a62a3f79415af2b7bf48324

**Comment by aubreyrjones** [comment]
I'm not sure exactly what you need here, but I currently support .globl/.global and .extern (as no ops, because they are default behavior).

I also define .hidden or .private, both of which isolate a global symbol to a given module. The hiding works both ways. If you need a more complicated scheme, please let me know.

**Comment by krasin** [comment]
Ok, thanks! Since LLVM backend already emits the linkage and nos_linker has enough support for these directives, I close this issue.
