### ISSUE TITLE
[debt] Do not emit preamble

### ISSUE THREAD

**Issue by krasin** [llvm-dcpu16/llvm-dcpu16#54]
Currently, the compiler outputs the preamble like described in #53. Once DCPU16 got the linker support, we need to get rid of this hack.

**Comment by aubreyrjones** [comment]
Please fix this, or offer it on a switch.

It's becoming painful to remove them by hand for testing.

**Comment by krasin** [comment]
Sure, just a sec

**Comment by krasin** [comment]
Is it better now?

**Comment by aubreyrjones** [comment]
It hasn't gone away. But, maybe I built it wrong? Do I need to do something special to build clang when I reissue make in the root llvm directory? I do see the .globl and .text showing up now.

Just to be sure we're talking about the same thing:

```
:autoinit               ;;Init data stack register C
  SET I, SP
  SUB I, 256
:autostart
  JSR main
:autohalt SET PC, autohalt
```

I'm happy to add that verbatim as a loader fragment, though, if you're attached to that sort of functionality.

But, what is the purpose of the autoinit, so that I can replicate it? Is I the stack pointer for y'all?  Or is autoinit the entry-point you want me to link against, not main?

**Comment by aubreyrjones** [comment]
I have to sleep. I'll try again tomorrow. But as of this instant (check timestamp), nos_link is digesting clang output.

**Comment by krasin** [comment]
The code emitting the preamble is gone: 78abe72f36fd31e96e8c035607e2877a5651fe7a.

Do you use prebuilt Clang or building it yourself? Currently, you have to clone / pull the latest sources and build them.

**Comment by aubreyrjones** [comment]
I pulled. I maybe got the wrong branch. I will try again tomorrow.

For now, i will assume it works and thank you!

**Comment by krasin** [comment]
You should always use dcpu16 branch and it's the default branch. 'See' you tomorrow. :)

**Comment by aubreyrjones** [comment]
After completely deleting source, cloning, and rebuilding, I am getting perfect output.

Thank you!
